/*
 imagesLoaded PACKAGED v4.1.3
 JavaScript is all like "You images are done yet or what?"
 MIT License
*/
!function(k,f){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",f):"object"==typeof module&&module.exports?module.exports=f():k.EvEmitter=f()}("undefined"!=typeof window?window:this,function(){function k(){}var f=k.prototype;return f.on=function(e,h){if(e&&h){var c=this._events=this._events||{};c=c[e]=c[e]||[];return-1==c.indexOf(h)&&c.push(h),this}},f.once=function(e,h){if(e&&h){this.on(e,h);var c=this._onceEvents=this._onceEvents||{};return(c[e]=c[e]||{})[h]=!0,this}},f.off=
function(e,h){var c=this._events&&this._events[e];if(c&&c.length){var g=c.indexOf(h);return-1!=g&&c.splice(g,1),this}},f.emitEvent=function(e,h){var c=this._events&&this._events[e];if(c&&c.length){var g=0,l=c[g];h=h||[];for(var m=this._onceEvents&&this._onceEvents[e];l;){var p=m&&m[l];p&&(this.off(e,l),delete m[l]);l.apply(this,h);g+=p?0:1;l=c[g]}return this}},f.allOff=f.removeAllListeners=function(){delete this._events;delete this._onceEvents},k});
(function(k,f){"function"==typeof define&&define.amd?define(["ev-emitter/ev-emitter"],function(e){return f(k,e)}):"object"==typeof module&&module.exports?module.exports=f(k,require("ev-emitter")):k.imagesLoaded=f(k,k.EvEmitter)})("undefined"!=typeof window?window:this,function(k,f){function e(a,b){for(var d in b)a[d]=b[d];return a}function h(a){var b=[];if(Array.isArray(a))b=a;else if("number"==typeof a.length)for(var d=0;d<a.length;d++)b.push(a[d]);else b.push(a);return b}function c(a,b,d){return this instanceof
c?("string"==typeof a&&(a=document.querySelectorAll(a)),this.elements=h(a),this.options=e({},this.options),"function"==typeof b?d=b:e(this.options,b),d&&this.on("always",d),this.getImages(),m&&(this.jqDeferred=new m.Deferred),void setTimeout(function(){this.check()}.bind(this))):new c(a,b,d)}function g(a){this.img=a}function l(a,b){this.url=a;this.element=b;this.img=new Image}var m=k.jQuery,p=k.console;c.prototype=Object.create(f.prototype);c.prototype.options={};c.prototype.getImages=function(){this.images=
[];this.elements.forEach(this.addElementImages,this)};c.prototype.addElementImages=function(a){"IMG"==a.nodeName&&this.addImage(a);!0===this.options.background&&this.addElementBackgroundImages(a);var b=a.nodeType;if(b&&q[b]){var d=a.querySelectorAll("img");for(b=0;b<d.length;b++)this.addImage(d[b]);if("string"==typeof this.options.background)for(a=a.querySelectorAll(this.options.background),b=0;b<a.length;b++)this.addElementBackgroundImages(a[b])}};var q={1:!0,9:!0,11:!0};return c.prototype.addElementBackgroundImages=
function(a){var b=getComputedStyle(a);if(b)for(var d=/url\((['"])?(.*?)\1\)/gi,n=d.exec(b.backgroundImage);null!==n;)(n=n&&n[2])&&this.addBackground(n,a),n=d.exec(b.backgroundImage)},c.prototype.addImage=function(a){a=new g(a);this.images.push(a)},c.prototype.addBackground=function(a,b){var d=new l(a,b);this.images.push(d)},c.prototype.check=function(){function a(d,n,r){setTimeout(function(){b.progress(d,n,r)})}var b=this;return this.progressedCount=0,this.hasAnyBroken=!1,this.images.length?void this.images.forEach(function(d){d.once("progress",
a);d.check()}):void this.complete()},c.prototype.progress=function(a,b,d){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;this.emitEvent("progress",[this,a,b]);this.jqDeferred&&this.jqDeferred.notify&&this.jqDeferred.notify(this,a);this.progressedCount==this.images.length&&this.complete();this.options.debug&&p&&p.log("progress: "+d,a,b)},c.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";if(this.isComplete=!0,this.emitEvent(a,[this]),this.emitEvent("always",
[this]),this.jqDeferred)this.jqDeferred[this.hasAnyBroken?"reject":"resolve"](this)},g.prototype=Object.create(f.prototype),g.prototype.check=function(){return this.getIsImageComplete()?void this.confirm(0!==this.img.naturalWidth,"naturalWidth"):(this.proxyImage=new Image,this.proxyImage.addEventListener("load",this),this.proxyImage.addEventListener("error",this),this.img.addEventListener("load",this),this.img.addEventListener("error",this),void(this.proxyImage.src=this.img.src))},g.prototype.getIsImageComplete=
function(){return this.img.complete&&void 0!==this.img.naturalWidth},g.prototype.confirm=function(a,b){this.isLoaded=a;this.emitEvent("progress",[this,this.img,b])},g.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},g.prototype.onload=function(){this.confirm(!0,"onload");this.unbindEvents()},g.prototype.onerror=function(){this.confirm(!1,"onerror");this.unbindEvents()},g.prototype.unbindEvents=function(){this.proxyImage.removeEventListener("load",this);this.proxyImage.removeEventListener("error",
this);this.img.removeEventListener("load",this);this.img.removeEventListener("error",this)},l.prototype=Object.create(g.prototype),l.prototype.check=function(){this.img.addEventListener("load",this);this.img.addEventListener("error",this);this.img.src=this.url;this.getIsImageComplete()&&(this.confirm(0!==this.img.naturalWidth,"naturalWidth"),this.unbindEvents())},l.prototype.unbindEvents=function(){this.img.removeEventListener("load",this);this.img.removeEventListener("error",this)},l.prototype.confirm=
function(a,b){this.isLoaded=a;this.emitEvent("progress",[this,this.element,b])},c.makeJQueryPlugin=function(a){(a=a||k.jQuery)&&(m=a,m.fn.imagesLoaded=function(b,d){return(new c(this,b,d)).jqDeferred.promise(m(this))})},c.makeJQueryPlugin(),c});