/*
 Infinite Scroll PACKAGED v3.0.2
 Automatically add next page

 Licensed GPLv3 for open source use
 or Infinite Scroll Commercial License for commercial use

 https://infinite-scroll.com
 Copyright 2017 Metafizzy
*/
!function(g,e){"function"==typeof define&&define.amd?define("jquery-bridget/jquery-bridget",["jquery"],function(l){return e(g,l)}):"object"==typeof module&&module.exports?module.exports=e(g,require("jquery")):g.jQueryBridget=e(g,g.jQuery)}(window,function(g,e){function l(k,n,p){function a(m,q,r){var t,u="$()."+k+'("'+q+'")';return m.each(function(y,x){var v=p.data(x,k);if(!v)return void h(k+" not initialized. Cannot call methods, i.e. "+u);var w=v[q];if(!w||"_"==q.charAt(0))return void h(u+" is not a valid method");
v=w.apply(v,r);t=void 0===t?v:t}),void 0!==t?t:m}function d(m,q){m.each(function(r,t){var u=p.data(t,k);u?(u.option(q),u._init()):(u=new n(t,q),p.data(t,k,u))})}(p=p||e||g.jQuery)&&(n.prototype.option||(n.prototype.option=function(m){p.isPlainObject(m)&&(this.options=p.extend(!0,this.options,m))}),p.fn[k]=function(m){if("string"==typeof m){var q=b.call(arguments,1);return a(this,m,q)}return d(this,m),this},f(p))}function f(k){!k||k&&k.bridget||(k.bridget=l)}var b=Array.prototype.slice,c=g.console,
h="undefined"==typeof c?function(){}:function(k){c.error(k)};return f(e||g.jQuery),l});
(function(g,e){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",e):"object"==typeof module&&module.exports?module.exports=e():g.EvEmitter=e()})("undefined"!=typeof window?window:this,function(){function g(){}var e=g.prototype;return e.on=function(l,f){if(l&&f){var b=this._events=this._events||{};b=b[l]=b[l]||[];return-1==b.indexOf(f)&&b.push(f),this}},e.once=function(l,f){if(l&&f){this.on(l,f);var b=this._onceEvents=this._onceEvents||{};return(b[l]=b[l]||{})[f]=!0,this}},e.off=
function(l,f){var b=this._events&&this._events[l];if(b&&b.length){var c=b.indexOf(f);return-1!=c&&b.splice(c,1),this}},e.emitEvent=function(l,f){var b=this._events&&this._events[l];if(b&&b.length){var c=0,h=b[c];f=f||[];for(var k=this._onceEvents&&this._onceEvents[l];h;){var n=k&&k[h];n&&(this.off(l,h),delete k[h]);h.apply(this,f);c+=n?0:1;h=b[c]}return this}},e.allOff=e.removeAllListeners=function(){delete this._events;delete this._onceEvents},g});
(function(g,e){"function"==typeof define&&define.amd?define("desandro-matches-selector/matches-selector",e):"object"==typeof module&&module.exports?module.exports=e():g.matchesSelector=e()})(window,function(){var g=function(){var e=window.Element.prototype;if(e.matches)return"matches";if(e.matchesSelector)return"matchesSelector";for(var l=["webkit","moz","ms","o"],f=0;f<l.length;f++){var b=l[f]+"MatchesSelector";if(e[b])return b}}();return function(e,l){return e[g](l)}});
(function(g,e){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["desandro-matches-selector/matches-selector"],function(l){return e(g,l)}):"object"==typeof module&&module.exports?module.exports=e(g,require("desandro-matches-selector")):g.fizzyUIUtils=e(g,g.matchesSelector)})(window,function(g,e){var l={extend:function(b,c){for(var h in c)b[h]=c[h];return b},modulo:function(b,c){return(b%c+c)%c},makeArray:function(b){var c=[];if(Array.isArray(b))c=b;else if(b&&"object"==typeof b&&
"number"==typeof b.length)for(var h=0;h<b.length;h++)c.push(b[h]);else c.push(b);return c},removeFrom:function(b,c){var h=b.indexOf(c);-1!=h&&b.splice(h,1)},getParent:function(b,c){for(;b.parentNode&&b!=document.body;)if(b=b.parentNode,e(b,c))return b},getQueryElement:function(b){return"string"==typeof b?document.querySelector(b):b},handleEvent:function(b){var c="on"+b.type;this[c]&&this[c](b)},filterFindElements:function(b,c){b=l.makeArray(b);var h=[];return b.forEach(function(k){if(k instanceof
HTMLElement){if(!c)return void h.push(k);e(k,c)&&h.push(k);k=k.querySelectorAll(c);for(var n=0;n<k.length;n++)h.push(k[n])}}),h},debounceMethod:function(b,c,h){var k=b.prototype[c],n=c+"Timeout";b.prototype[c]=function(){var p=this[n];p&&clearTimeout(p);var a=arguments,d=this;this[n]=setTimeout(function(){k.apply(d,a);delete d[n]},h||100)}},docReady:function(b){var c=document.readyState;"complete"==c||"interactive"==c?setTimeout(b):document.addEventListener("DOMContentLoaded",b)},toDashed:function(b){return b.replace(/(.)([A-Z])/g,
function(c,h,k){return h+"-"+k}).toLowerCase()}},f=g.console;return l.htmlInit=function(b,c){l.docReady(function(){var h=l.toDashed(c),k="data-"+h,n=document.querySelectorAll("["+k+"]");h=document.querySelectorAll(".js-"+h);n=l.makeArray(n).concat(l.makeArray(h));var p=k+"-options",a=g.jQuery;n.forEach(function(d){var m=d.getAttribute(k)||d.getAttribute(p);try{var q=m&&JSON.parse(m)}catch(r){return void(f&&f.error("Error parsing "+k+" on "+d.className+": "+r))}q=new b(d,q);a&&a.data(d,c,q)})})},l});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/core",["ev-emitter/ev-emitter","fizzy-ui-utils/utils"],function(l,f){return e(g,l,f)}):"object"==typeof module&&module.exports?module.exports=e(g,require("ev-emitter"),require("fizzy-ui-utils")):g.InfiniteScroll=e(g,g.EvEmitter,g.fizzyUIUtils)})(window,function(g,e,l){function f(a,d){var m=l.getQueryElement(a);if(!m)return void console.error("Bad element for InfiniteScroll: "+(m||a));if(a=m,a.infiniteScrollGUID)return m=
c[a.infiniteScrollGUID],m.option(d),m;this.element=a;this.options=l.extend({},f.defaults);this.option(d);b&&(this.$element=b(this.element));this.create()}var b=g.jQuery,c={};f.defaults={};f.create={};f.destroy={};var h=f.prototype;l.extend(h,e.prototype);var k=0;h.create=function(){var a=this.guid=++k;if(this.element.infiniteScrollGUID=a,c[a]=this,this.pageIndex=1,this.loadCount=0,this.updateGetPath(),!this.getPath)return void console.error("Disabling InfiniteScroll");this.updateGetAbsolutePath();
this.log("initialized",[this.element.className]);this.callOnInit();for(var d in f.create)f.create[d].call(this)};h.option=function(a){l.extend(this.options,a)};h.callOnInit=function(){var a=this.options.onInit;a&&a.call(this,this)};h.dispatchEvent=function(a,d,m){this.log(a,m);var q=d?[d].concat(m):m;if(this.emitEvent(a,q),b&&this.$element)q=a+=".infiniteScroll",d&&(d=b.Event(d),d.type=a,q=d),this.$element.trigger(q,m)};var n={initialized:function(a){return"on "+a},request:function(a){return"URL: "+
a},load:function(a,d){return(a.title||"")+". URL: "+d},error:function(a,d){return a+". URL: "+d},append:function(a,d,m){return m.length+" items. URL: "+d},last:function(a,d){return"URL: "+d},history:function(a,d){return"URL: "+d},pageIndex:function(a,d){return"current page determined to be: "+a+" from "+d}};h.log=function(a,d){if(this.options.debug){var m="[InfiniteScroll] "+a,q=n[a];q&&(m+=". "+q.apply(this,d));console.log(m)}};h.updateMeasurements=function(){this.windowHeight=g.innerHeight;this.top=
this.element.getBoundingClientRect().top+g.pageYOffset};h.updateScroller=function(){var a=this.options.elementScroll;if(!a)return void(this.scroller=g);if(this.scroller=!0===a?this.element:l.getQueryElement(a),!this.scroller)throw"Unable to find elementScroll: "+a;};h.updateGetPath=function(){var a=this.options.path;if(!a)return void console.error("InfiniteScroll path option required. Set as: "+a);var d=typeof a;return"function"==d?void(this.getPath=a):"string"==d&&a.match("{{#}}")?void this.updateGetPathTemplate(a):
void this.updateGetPathSelector(a)};h.updateGetPathTemplate=function(a){this.getPath=function(){return a.replace("{{#}}",this.pageIndex+1)}.bind(this);var d=a.replace("{{#}}","(\\d\\d?\\d?)");(d=location.href.match(new RegExp(d)))&&(this.pageIndex=parseInt(d[1],10),this.log("pageIndex",this.pageIndex,"template string"))};var p=[/^(.*?\/?page\/?)(\d\d?\d?)(.*?$)/,/^(.*?\/?\?page=)(\d\d?\d?)(.*?$)/,/(.*?)(\d\d?\d?)(?!.*\d)(.*?$)/];return h.updateGetPathSelector=function(a){var d=document.querySelector(a);
if(!d)return void console.error("Bad InfiniteScroll path option. Next link not found: "+a);a=d.getAttribute("href");for(d=0;a&&d<p.length;d++){var m=p[d];if(m=a.match(m)){var q=m.slice(1);break}}return q?(this.isPathSelector=!0,this.getPath=function(){return q[0]+(this.pageIndex+1)+q[2]}.bind(this),this.pageIndex=parseInt(q[1],10)-1,void this.log("pageIndex",[this.pageIndex,"next link"])):void console.error("InfiniteScroll unable to parse next link href: "+a)},h.updateGetAbsolutePath=function(){var a=
this.getPath();if(a.match(/^http/)||a.match(/^\//))return void(this.getAbsolutePath=this.getPath);a=location.pathname;var d=a.substring(0,a.lastIndexOf("/"));this.getAbsolutePath=function(){return d+"/"+this.getPath()}},f.create.hideNav=function(){var a=l.getQueryElement(this.options.hideNav);a&&(a.style.display="none",this.nav=a)},f.destroy.hideNav=function(){this.nav&&(this.nav.style.display="")},h.destroy=function(){this.allOff();for(var a in f.destroy)f.destroy[a].call(this);delete this.element.infiniteScrollGUID;
delete c[this.guid]},f.throttle=function(a,d){d=d||200;var m,q;return function(){var r=+new Date,t=arguments,u=function(){m=r;a.apply(this,t)}.bind(this);m&&r<m+d?(clearTimeout(q),q=setTimeout(u,d)):u()}},f.data=function(a){return(a=(a=l.getQueryElement(a))&&a.infiniteScrollGUID)&&c[a]},f.setJQuery=function(a){b=a},l.htmlInit(f,"infinite-scroll"),b&&b.bridget&&b.bridget("infiniteScroll",f),f});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/page-load",["./core"],function(l){return e(g,l)}):"object"==typeof module&&module.exports?module.exports=e(g,require("./core")):e(g,g.InfiniteScroll)})(window,function(g,e){function l(c){for(var h=document.createDocumentFragment(),k=0;c&&k<c.length;k++)h.appendChild(c[k]);return h}function f(c,h,k,n){var p=new XMLHttpRequest;p.open("GET",c,!0);p.responseType=h||"";p.setRequestHeader("X-Requested-With","XMLHttpRequest");
p.onload=function(){200==p.status?k(p.response):n(Error(p.statusText))};p.onerror=function(){n(Error("Network error requesting "+c))};p.send()}var b=e.prototype;return e.defaults.loadOnScroll=!0,e.defaults.checkLastPage=!0,e.defaults.responseType="document",e.create.pageLoad=function(){this.canLoad=!0;this.on("scrollThreshold",this.onScrollThresholdLoad);this.on("append",this.checkLastPage);this.options.outlayer&&this.on("append",this.onAppendOutlayer)},b.onScrollThresholdLoad=function(){this.options.loadOnScroll&&
this.loadNextPage()},b.loadNextPage=function(){if(!this.isLoading&&this.canLoad){var c=this.getAbsolutePath();this.isLoading=!0;var h=function(n){this.onPageLoad(n,c)}.bind(this),k=function(n){this.onPageError(n,c)}.bind(this);f(c,this.options.responseType,h,k);this.dispatchEvent("request",null,[c])}},b.onPageLoad=function(c,h){return this.options.append||(this.isLoading=!1),this.pageIndex++,this.loadCount++,this.dispatchEvent("load",null,[c,h]),this.appendNextPage(c,h),c},b.appendNextPage=function(c,
h){var k=this.options.append;if("document"==this.options.responseType&&k){var n=c.querySelectorAll(k),p=l(n);k=function(){this.appendItems(n,p);this.isLoading=!1;this.dispatchEvent("append",null,[c,h,n])}.bind(this);this.options.outlayer?this.appendOutlayerItems(p,k):k()}},b.appendItems=function(c,h){if(c&&c.length){h=h||l(c);for(var k=h.querySelectorAll("script"),n=0;n<k.length;n++){for(var p=k[n],a=document.createElement("script"),d=a,m=p.attributes,q=0;q<m.length;q++){var r=m[q];d.setAttribute(r.name,
r.value)}p.parentNode.replaceChild(a,p)}this.element.appendChild(h)}},b.appendOutlayerItems=function(c,h){var k=e.imagesLoaded||g.imagesLoaded;return k?void k(c,h):(console.error("[InfiniteScroll] imagesLoaded required for outlayer option"),void(this.isLoading=!1))},b.onAppendOutlayer=function(c,h,k){this.options.outlayer.appended(k)},b.checkLastPage=function(c,h){var k=this.options.checkLastPage;if(k){var n=this.options.path;if("function"==typeof n&&!this.getPath())return void this.lastPageReached(c,
h);var p;if("string"==typeof k?p=k:this.isPathSelector&&(p=n),p&&c.querySelector)c.querySelector(p)||this.lastPageReached(c,h)}},b.lastPageReached=function(c,h){this.canLoad=!1;this.dispatchEvent("last",null,[c,h])},b.onPageError=function(c,h){return this.isLoading=!1,this.canLoad=!1,this.dispatchEvent("error",null,[c,h]),c},e.create.prefill=function(){if(this.options.prefill){var c=this.options.append;if(!c)return void console.error("append option required for prefill. Set as :"+c);this.updateMeasurements();
this.updateScroller();this.isPrefilling=!0;this.on("append",this.prefill);this.once("error",this.stopPrefill);this.once("last",this.stopPrefill);this.prefill()}},b.prefill=function(){(this.isPrefilling=0<=this.getPrefillDistance())?(this.log("prefill"),this.loadNextPage()):this.stopPrefill()},b.getPrefillDistance=function(){return this.options.elementScroll?this.scroller.clientHeight-this.scroller.scrollHeight:this.windowHeight-this.element.clientHeight},b.stopPrefill=function(){console.log("stopping prefill");
this.off("append",this.prefill)},e});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/scroll-watch",["./core","fizzy-ui-utils/utils"],function(l,f){return e(g,l,f)}):"object"==typeof module&&module.exports?module.exports=e(g,require("./core"),require("fizzy-ui-utils")):e(g,g.InfiniteScroll,g.fizzyUIUtils)})(window,function(g,e,l){var f=e.prototype;return e.defaults.scrollThreshold=400,e.create.scrollWatch=function(){this.pageScrollHandler=this.onPageScroll.bind(this);this.resizeHandler=this.onResize.bind(this);
var b=this.options.scrollThreshold;(b||0===b)&&this.enableScrollWatch()},e.destroy.scrollWatch=function(){this.disableScrollWatch()},f.enableScrollWatch=function(){this.isScrollWatching||(this.isScrollWatching=!0,this.updateMeasurements(),this.updateScroller(),this.on("last",this.disableScrollWatch),this.bindScrollWatchEvents(!0))},f.disableScrollWatch=function(){this.isScrollWatching&&(this.bindScrollWatchEvents(!1),delete this.isScrollWatching)},f.bindScrollWatchEvents=function(b){b=b?"addEventListener":
"removeEventListener";this.scroller[b]("scroll",this.pageScrollHandler);g[b]("resize",this.resizeHandler)},f.onPageScroll=e.throttle(function(){this.getBottomDistance()<=this.options.scrollThreshold&&this.dispatchEvent("scrollThreshold")}),f.getBottomDistance=function(){return this.options.elementScroll?this.getElementBottomDistance():this.getWindowBottomDistance()},f.getWindowBottomDistance=function(){return this.top+this.element.clientHeight-(g.pageYOffset+this.windowHeight)},f.getElementBottomDistance=
function(){return this.scroller.scrollHeight-(this.scroller.scrollTop+this.scroller.clientHeight)},f.onResize=function(){this.updateMeasurements()},l.debounceMethod(e,"onResize",150),e});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/history",["./core","fizzy-ui-utils/utils"],function(l,f){return e(g,l,f)}):"object"==typeof module&&module.exports?module.exports=e(g,require("./core"),require("fizzy-ui-utils")):e(g,g.InfiniteScroll,g.fizzyUIUtils)})(window,function(g,e,l){var f=e.prototype;e.defaults.history="replace";var b=document.createElement("a");return e.create.history=function(){if(this.options.history)return b.href=this.getAbsolutePath(),(b.origin||
b.protocol+"//"+b.host)==location.origin?void(this.options.append?this.createHistoryAppend():this.createHistoryPageLoad()):void console.error("[InfiniteScroll] cannot set history with different origin: "+b.origin+" on "+location.origin+" . History behavior disabled.")},f.createHistoryAppend=function(){this.updateMeasurements();this.updateScroller();this.scrollPages=[{top:0,path:location.href,title:document.title}];this.scrollPageIndex=0;this.scrollHistoryHandler=this.onScrollHistory.bind(this);this.unloadHandler=
this.onUnload.bind(this);this.scroller.addEventListener("scroll",this.scrollHistoryHandler);this.on("append",this.onAppendHistory);this.bindHistoryAppendEvents(!0)},f.bindHistoryAppendEvents=function(c){c=c?"addEventListener":"removeEventListener";this.scroller[c]("scroll",this.scrollHistoryHandler);g[c]("unload",this.unloadHandler)},f.createHistoryPageLoad=function(){this.on("load",this.onPageLoadHistory)},e.destroy.history=f.destroyHistory=function(){this.options.history&&this.options.append&&this.bindHistoryAppendEvents(!1)},
f.onAppendHistory=function(c,h,k){k=this.getElementScrollY(k[0]);b.href=h;this.scrollPages.push({top:k,path:b.href,title:c.title})},f.getElementScrollY=function(c){return this.options.elementScroll?this.getElementElementScrollY(c):this.getElementWindowScrollY(c)},f.getElementWindowScrollY=function(c){return c.getBoundingClientRect().top+g.pageYOffset},f.getElementElementScrollY=function(c){return c.offsetTop-this.top},f.onScrollHistory=function(){for(var c,h,k=this.getScrollViewY(),n=0;n<this.scrollPages.length;n++){var p=
this.scrollPages[n];if(p.top>=k)break;c=n;h=p}c!=this.scrollPageIndex&&(this.scrollPageIndex=c,this.setHistory(h.title,h.path))},l.debounceMethod(e,"onScrollHistory",150),f.getScrollViewY=function(){return this.options.elementScroll?this.scroller.scrollTop+this.scroller.clientHeight/2:g.pageYOffset+this.windowHeight/2},f.setHistory=function(c,h){var k=this.options.history;k&&history[k+"State"]&&(history[k+"State"](null,c,h),this.options.historyTitle&&(document.title=c),this.dispatchEvent("history",
null,[c,h]))},f.onUnload=function(){var c=this.scrollPageIndex;0!==c&&(c=g.pageYOffset-this.scrollPages[c].top+this.top,this.destroyHistory(),scrollTo(0,c))},f.onPageLoadHistory=function(c,h){this.setHistory(c.title,h)},e});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/button",["./core","fizzy-ui-utils/utils"],function(l,f){return e(g,l,f)}):"object"==typeof module&&module.exports?module.exports=e(g,require("./core"),require("fizzy-ui-utils")):e(g,g.InfiniteScroll,g.fizzyUIUtils)})(window,function(g,e,l){function f(b,c){this.element=b;this.infScroll=c;this.clickHandler=this.onClick.bind(this);this.element.addEventListener("click",this.clickHandler);c.on("request",this.disable.bind(this));
c.on("load",this.enable.bind(this));c.on("error",this.hide.bind(this));c.on("last",this.hide.bind(this))}return e.create.button=function(){var b=l.getQueryElement(this.options.button);if(b)return void(this.button=new f(b,this))},e.destroy.button=function(){this.button&&this.button.destroy()},f.prototype.onClick=function(b){b.preventDefault();this.infScroll.loadNextPage()},f.prototype.enable=function(){this.element.removeAttribute("disabled")},f.prototype.disable=function(){this.element.disabled="disabled"},
f.prototype.hide=function(){this.element.style.display="none"},f.prototype.destroy=function(){this.element.removeEventListener("click",this.clickHandler)},e.Button=f,e});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/status",["./core","fizzy-ui-utils/utils"],function(l,f){return e(g,l,f)}):"object"==typeof module&&module.exports?module.exports=e(g,require("./core"),require("fizzy-ui-utils")):e(g,g.InfiniteScroll,g.fizzyUIUtils)})(window,function(g,e,l){g=e.prototype;return e.create.status=function(){var f=l.getQueryElement(this.options.status);f&&(this.statusElement=f,this.statusEventElements={request:f.querySelector(".infinite-scroll-request"),
error:f.querySelector(".infinite-scroll-error"),last:f.querySelector(".infinite-scroll-last")},this.on("request",this.showRequestStatus),this.on("error",this.showErrorStatus),this.on("last",this.showLastStatus),this.bindHideStatus("on"))},g.bindHideStatus=function(f){this[f](this.options.append?"append":"load",this.hideAllStatus)},g.showRequestStatus=function(){this.showStatus("request")},g.showErrorStatus=function(){this.showStatus("error")},g.showLastStatus=function(){this.showStatus("last");this.bindHideStatus("off")},
g.showStatus=function(f){var b=this.statusElement;b&&(b.style.display="block");this.hideStatusEventElements();(f=this.statusEventElements[f])&&(f.style.display="block")},g.hideAllStatus=function(){var f=this.statusElement;f&&(f.style.display="none");this.hideStatusEventElements()},g.hideStatusEventElements=function(){for(var f in this.statusEventElements){var b=this.statusEventElements[f];b&&(b.style.display="none")}},e});
(function(g,e){"function"==typeof define&&define.amd?define("infinite-scroll/js/core infinite-scroll/js/page-load infinite-scroll/js/scroll-watch infinite-scroll/js/history infinite-scroll/js/button infinite-scroll/js/status".split(" "),e):"object"==typeof module&&module.exports&&(module.exports=e(require("./core"),require("./page-load"),require("./scroll-watch"),require("./history"),require("./button"),require("./status")))})(window,function(g){return g});
(function(g,e){"function"==typeof define&&define.amd?define("imagesloaded/imagesloaded",["ev-emitter/ev-emitter"],function(l){return e(g,l)}):"object"==typeof module&&module.exports?module.exports=e(g,require("ev-emitter")):g.imagesLoaded=e(g,g.EvEmitter)})("undefined"!=typeof window?window:this,function(g,e){function l(a,d){for(var m in d)a[m]=d[m];return a}function f(a){var d=[];if(Array.isArray(a))d=a;else if("number"==typeof a.length)for(var m=0;m<a.length;m++)d.push(a[m]);else d.push(a);return d}
function b(a,d,m){return this instanceof b?("string"==typeof a&&(a=document.querySelectorAll(a)),this.elements=f(a),this.options=l({},this.options),"function"==typeof d?m=d:l(this.options,d),m&&this.on("always",m),this.getImages(),k&&(this.jqDeferred=new k.Deferred),void setTimeout(function(){this.check()}.bind(this))):new b(a,d,m)}function c(a){this.img=a}function h(a,d){this.url=a;this.element=d;this.img=new Image}var k=g.jQuery,n=g.console;b.prototype=Object.create(e.prototype);b.prototype.options=
{};b.prototype.getImages=function(){this.images=[];this.elements.forEach(this.addElementImages,this)};b.prototype.addElementImages=function(a){"IMG"==a.nodeName&&this.addImage(a);!0===this.options.background&&this.addElementBackgroundImages(a);var d=a.nodeType;if(d&&p[d]){var m=a.querySelectorAll("img");for(d=0;d<m.length;d++)this.addImage(m[d]);if("string"==typeof this.options.background)for(a=a.querySelectorAll(this.options.background),d=0;d<a.length;d++)this.addElementBackgroundImages(a[d])}};
var p={1:!0,9:!0,11:!0};return b.prototype.addElementBackgroundImages=function(a){var d=getComputedStyle(a);if(d)for(var m=/url\((['"])?(.*?)\1\)/gi,q=m.exec(d.backgroundImage);null!==q;)(q=q&&q[2])&&this.addBackground(q,a),q=m.exec(d.backgroundImage)},b.prototype.addImage=function(a){a=new c(a);this.images.push(a)},b.prototype.addBackground=function(a,d){var m=new h(a,d);this.images.push(m)},b.prototype.check=function(){function a(m,q,r){setTimeout(function(){d.progress(m,q,r)})}var d=this;return this.progressedCount=
0,this.hasAnyBroken=!1,this.images.length?void this.images.forEach(function(m){m.once("progress",a);m.check()}):void this.complete()},b.prototype.progress=function(a,d,m){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;this.emitEvent("progress",[this,a,d]);this.jqDeferred&&this.jqDeferred.notify&&this.jqDeferred.notify(this,a);this.progressedCount==this.images.length&&this.complete();this.options.debug&&n&&n.log("progress: "+m,a,d)},b.prototype.complete=function(){var a=this.hasAnyBroken?
"fail":"done";if(this.isComplete=!0,this.emitEvent(a,[this]),this.emitEvent("always",[this]),this.jqDeferred)this.jqDeferred[this.hasAnyBroken?"reject":"resolve"](this)},c.prototype=Object.create(e.prototype),c.prototype.check=function(){return this.getIsImageComplete()?void this.confirm(0!==this.img.naturalWidth,"naturalWidth"):(this.proxyImage=new Image,this.proxyImage.addEventListener("load",this),this.proxyImage.addEventListener("error",this),this.img.addEventListener("load",this),this.img.addEventListener("error",
this),void(this.proxyImage.src=this.img.src))},c.prototype.getIsImageComplete=function(){return this.img.complete&&void 0!==this.img.naturalWidth},c.prototype.confirm=function(a,d){this.isLoaded=a;this.emitEvent("progress",[this,this.img,d])},c.prototype.handleEvent=function(a){var d="on"+a.type;this[d]&&this[d](a)},c.prototype.onload=function(){this.confirm(!0,"onload");this.unbindEvents()},c.prototype.onerror=function(){this.confirm(!1,"onerror");this.unbindEvents()},c.prototype.unbindEvents=function(){this.proxyImage.removeEventListener("load",
this);this.proxyImage.removeEventListener("error",this);this.img.removeEventListener("load",this);this.img.removeEventListener("error",this)},h.prototype=Object.create(c.prototype),h.prototype.check=function(){this.img.addEventListener("load",this);this.img.addEventListener("error",this);this.img.src=this.url;this.getIsImageComplete()&&(this.confirm(0!==this.img.naturalWidth,"naturalWidth"),this.unbindEvents())},h.prototype.unbindEvents=function(){this.img.removeEventListener("load",this);this.img.removeEventListener("error",
this)},h.prototype.confirm=function(a,d){this.isLoaded=a;this.emitEvent("progress",[this,this.element,d])},b.makeJQueryPlugin=function(a){(a=a||g.jQuery)&&(k=a,k.fn.imagesLoaded=function(d,m){return(new b(this,d,m)).jqDeferred.promise(k(this))})},b.makeJQueryPlugin(),b});