/*
 Masonry PACKAGED v4.2.0
 Cascading grid layout library
 http://masonry.desandro.com
 MIT License
 by David DeSandro
*/
!function(m,p){"function"==typeof define&&define.amd?define("jquery-bridget/jquery-bridget",["jquery"],function(r){return p(m,r)}):"object"==typeof module&&module.exports?module.exports=p(m,require("jquery")):m.jQueryBridget=p(m,m.jQuery)}(window,function(m,p){function r(f,u,t){function q(c,n,a){var d,h="$()."+f+'("'+n+'")';return c.each(function(v,w){var x=t.data(w,f);if(!x)return void k(f+" not initialized. Cannot call methods, i.e. "+h);var y=x[n];if(!y||"_"==n.charAt(0))return void k(h+" is not a valid method");
x=y.apply(x,a);d=void 0===d?x:d}),void 0!==d?d:c}function e(c,n){c.each(function(a,d){var h=t.data(d,f);h?(h.option(n),h._init()):(h=new u(d,n),t.data(d,f,h))})}(t=t||p||m.jQuery)&&(u.prototype.option||(u.prototype.option=function(c){t.isPlainObject(c)&&(this.options=t.extend(!0,this.options,c))}),t.fn[f]=function(c){if("string"==typeof c){var n=b.call(arguments,1);return q(this,c,n)}return e(this,c),this},l(t))}function l(f){!f||f&&f.bridget||(f.bridget=r)}var b=Array.prototype.slice,g=m.console,
k="undefined"==typeof g?function(){}:function(f){g.error(f)};return l(p||m.jQuery),r});
(function(m,p){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",p):"object"==typeof module&&module.exports?module.exports=p():m.EvEmitter=p()})("undefined"!=typeof window?window:this,function(){function m(){}var p=m.prototype;return p.on=function(r,l){if(r&&l){var b=this._events=this._events||{};b=b[r]=b[r]||[];return-1==b.indexOf(l)&&b.push(l),this}},p.once=function(r,l){if(r&&l){this.on(r,l);var b=this._onceEvents=this._onceEvents||{};return(b[r]=b[r]||{})[l]=!0,this}},p.off=
function(r,l){var b=this._events&&this._events[r];if(b&&b.length){var g=b.indexOf(l);return-1!=g&&b.splice(g,1),this}},p.emitEvent=function(r,l){var b=this._events&&this._events[r];if(b&&b.length){var g=0,k=b[g];l=l||[];for(var f=this._onceEvents&&this._onceEvents[r];k;){var u=f&&f[k];u&&(this.off(r,k),delete f[k]);k.apply(this,l);g+=u?0:1;k=b[g]}return this}},m});
(function(m,p){"function"==typeof define&&define.amd?define("get-size/get-size",[],function(){return p()}):"object"==typeof module&&module.exports?module.exports=p():m.getSize=p()})(window,function(){function m(t){var q=parseFloat(t);return-1==t.indexOf("%")&&!isNaN(q)&&q}function p(){}function r(t){t=getComputedStyle(t);return t||g("Style returned "+t+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),t}function l(t){if(!u){u=!0;var q=document.createElement("div");
q.style.width="200px";q.style.padding="1px 2px 3px 4px";q.style.borderStyle="solid";q.style.borderWidth="1px 2px 3px 4px";q.style.boxSizing="border-box";var e=document.body||document.documentElement;e.appendChild(q);var c=r(q);l.isBoxSizeOuter=b=200==m(c.width);e.removeChild(q)}if("string"==typeof t&&(t=document.querySelector(t)),t&&"object"==typeof t&&t.nodeType){e=r(t);if("none"==e.display){q={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0};for(e=0;f>e;e++)q[k[e]]=0;return q}q=
{};q.width=t.offsetWidth;q.height=t.offsetHeight;t=q.isBorderBox="border-box"==e.boxSizing;for(c=0;f>c;c++){var n=k[c],a=parseFloat(e[n]);q[n]=isNaN(a)?0:a}c=q.paddingLeft+q.paddingRight;n=q.paddingTop+q.paddingBottom;a=q.marginLeft+q.marginRight;var d=q.marginTop+q.marginBottom,h=q.borderLeftWidth+q.borderRightWidth,v=q.borderTopWidth+q.borderBottomWidth;t=t&&b;var w=m(e.width);!1!==w&&(q.width=w+(t?0:c+h));e=m(e.height);return!1!==e&&(q.height=e+(t?0:n+v)),q.innerWidth=q.width-(c+h),q.innerHeight=
q.height-(n+v),q.outerWidth=q.width+a,q.outerHeight=q.height+d,q}}var b,g="undefined"==typeof console?p:function(t){console.error(t)},k="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" "),f=k.length,u=!1;return l});
(function(m,p){"function"==typeof define&&define.amd?define("desandro-matches-selector/matches-selector",p):"object"==typeof module&&module.exports?module.exports=p():m.matchesSelector=p()})(window,function(){var m=function(){var p=window.Element.prototype;if(p.matches)return"matches";if(p.matchesSelector)return"matchesSelector";for(var r=["webkit","moz","ms","o"],l=0;l<r.length;l++){var b=r[l]+"MatchesSelector";if(p[b])return b}}();return function(p,r){return p[m](r)}});
(function(m,p){"function"==typeof define&&define.amd?define("fizzy-ui-utils/utils",["desandro-matches-selector/matches-selector"],function(r){return p(m,r)}):"object"==typeof module&&module.exports?module.exports=p(m,require("desandro-matches-selector")):m.fizzyUIUtils=p(m,m.matchesSelector)})(window,function(m,p){var r={extend:function(b,g){for(var k in g)b[k]=g[k];return b},modulo:function(b,g){return(b%g+g)%g},makeArray:function(b){var g=[];if(Array.isArray(b))g=b;else if(b&&"object"==typeof b&&
"number"==typeof b.length)for(var k=0;k<b.length;k++)g.push(b[k]);else g.push(b);return g},removeFrom:function(b,g){var k=b.indexOf(g);-1!=k&&b.splice(k,1)},getParent:function(b,g){for(;b!=document.body;)if(b=b.parentNode,p(b,g))return b},getQueryElement:function(b){return"string"==typeof b?document.querySelector(b):b},handleEvent:function(b){var g="on"+b.type;this[g]&&this[g](b)},filterFindElements:function(b,g){b=r.makeArray(b);var k=[];return b.forEach(function(f){if(f instanceof HTMLElement){if(!g)return void k.push(f);
p(f,g)&&k.push(f);f=f.querySelectorAll(g);for(var u=0;u<f.length;u++)k.push(f[u])}}),k},debounceMethod:function(b,g,k){var f=b.prototype[g],u=g+"Timeout";b.prototype[g]=function(){var t=this[u];t&&clearTimeout(t);var q=arguments,e=this;this[u]=setTimeout(function(){f.apply(e,q);delete e[u]},k||100)}},docReady:function(b){var g=document.readyState;"complete"==g||"interactive"==g?setTimeout(b):document.addEventListener("DOMContentLoaded",b)},toDashed:function(b){return b.replace(/(.)([A-Z])/g,function(g,
k,f){return k+"-"+f}).toLowerCase()}},l=m.console;return r.htmlInit=function(b,g){r.docReady(function(){var k=r.toDashed(g),f="data-"+k,u=document.querySelectorAll("["+f+"]");k=document.querySelectorAll(".js-"+k);u=r.makeArray(u).concat(r.makeArray(k));var t=f+"-options",q=m.jQuery;u.forEach(function(e){var c=e.getAttribute(f)||e.getAttribute(t);try{var n=c&&JSON.parse(c)}catch(a){return void(l&&l.error("Error parsing "+f+" on "+e.className+": "+a))}n=new b(e,n);q&&q.data(e,g,n)})})},r});
(function(m,p){"function"==typeof define&&define.amd?define("outlayer/item",["ev-emitter/ev-emitter","get-size/get-size"],p):"object"==typeof module&&module.exports?module.exports=p(require("ev-emitter"),require("get-size")):(m.Outlayer={},m.Outlayer.Item=p(m.EvEmitter,m.getSize))})(window,function(m,p){function r(e,c){e&&(this.element=e,this.layout=c,this.position={x:0,y:0},this._create())}var l=document.documentElement.style,b="string"==typeof l.transition?"transition":"WebkitTransition";l="string"==
typeof l.transform?"transform":"WebkitTransform";var g={WebkitTransition:"webkitTransitionEnd",transition:"transitionend"}[b],k={transform:l,transition:b,transitionDuration:b+"Duration",transitionProperty:b+"Property",transitionDelay:b+"Delay"},f=r.prototype=Object.create(m.prototype);f.constructor=r;f._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}};this.css({position:"absolute"})};f.handleEvent=function(e){var c="on"+e.type;this[c]&&this[c](e)};f.getSize=function(){this.size=
p(this.element)};f.css=function(e){var c=this.element.style,n;for(n in e)c[k[n]||n]=e[n]};f.getPosition=function(){var e=getComputedStyle(this.element),c=this.layout._getOption("originLeft"),n=this.layout._getOption("originTop"),a=e[c?"left":"right"],d=e[n?"top":"bottom"];e=this.layout.size;a=-1!=a.indexOf("%")?parseFloat(a)/100*e.width:parseInt(a,10);d=-1!=d.indexOf("%")?parseFloat(d)/100*e.height:parseInt(d,10);a=isNaN(a)?0:a;d=isNaN(d)?0:d;a-=c?e.paddingLeft:e.paddingRight;d-=n?e.paddingTop:e.paddingBottom;
this.position.x=a;this.position.y=d};f.layoutPosition=function(){var e=this.layout.size,c={},n=this.layout._getOption("originLeft"),a=this.layout._getOption("originTop"),d=n?"right":"left";c[n?"left":"right"]=this.getXValue(this.position.x+e[n?"paddingLeft":"paddingRight"]);c[d]="";n=a?"bottom":"top";c[a?"top":"bottom"]=this.getYValue(this.position.y+e[a?"paddingTop":"paddingBottom"]);c[n]="";this.css(c);this.emitEvent("layout",[this])};f.getXValue=function(e){var c=this.layout._getOption("horizontal");
return this.layout.options.percentPosition&&!c?e/this.layout.size.width*100+"%":e+"px"};f.getYValue=function(e){var c=this.layout._getOption("horizontal");return this.layout.options.percentPosition&&c?e/this.layout.size.height*100+"%":e+"px"};f._transitionTo=function(e,c){this.getPosition();var n=this.position.x,a=this.position.y,d=parseInt(e,10),h=parseInt(c,10);d=d===this.position.x&&h===this.position.y;if(this.setPosition(e,c),d&&!this.isTransitioning)return void this.layoutPosition();d={};d.transform=
this.getTranslate(e-n,c-a);this.transition({to:d,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})};f.getTranslate=function(e,c){var n=this.layout._getOption("originLeft"),a=this.layout._getOption("originTop");return e=n?e:-e,c=a?c:-c,"translate3d("+e+"px, "+c+"px, 0)"};f.goTo=function(e,c){this.setPosition(e,c);this.layoutPosition()};f.moveTo=f._transitionTo;f.setPosition=function(e,c){this.position.x=parseInt(e,10);this.position.y=parseInt(c,10)};f._nonTransition=function(e){this.css(e.to);
e.isCleaning&&this._removeStyles(e.to);for(var c in e.onTransitionEnd)e.onTransitionEnd[c].call(this)};f.transition=function(e){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(e);var c=this._transn,n;for(n in e.onTransitionEnd)c.onEnd[n]=e.onTransitionEnd[n];for(n in e.to)c.ingProperties[n]=!0,e.isCleaning&&(c.clean[n]=!0);e.from&&this.css(e.from);this.enableTransition(e.to);this.css(e.to);this.isTransitioning=!0};var u="opacity,"+function(e){return e.replace(/([A-Z])/g,
function(c){return"-"+c.toLowerCase()})}(l);f.enableTransition=function(){if(!this.isTransitioning){var e=this.layout.options.transitionDuration;this.css({transitionProperty:u,transitionDuration:"number"==typeof e?e+"ms":e,transitionDelay:this.staggerDelay||0});this.element.addEventListener(g,this,!1)}};f.onwebkitTransitionEnd=function(e){this.ontransitionend(e)};f.onotransitionend=function(e){this.ontransitionend(e)};var t={"-webkit-transform":"transform"};f.ontransitionend=function(e){if(e.target===
this.element){var c=this._transn,n=t[e.propertyName]||e.propertyName;delete c.ingProperties[n];a:{for(a in c.ingProperties){var a=!1;break a}a=!0}if(a&&this.disableTransition(),n in c.clean&&(this.element.style[e.propertyName]="",delete c.clean[n]),n in c.onEnd)c.onEnd[n].call(this),delete c.onEnd[n];this.emitEvent("transitionEnd",[this])}};f.disableTransition=function(){this.removeTransitionStyles();this.element.removeEventListener(g,this,!1);this.isTransitioning=!1};f._removeStyles=function(e){var c=
{},n;for(n in e)c[n]="";this.css(c)};var q={transitionProperty:"",transitionDuration:"",transitionDelay:""};return f.removeTransitionStyles=function(){this.css(q)},f.stagger=function(e){e=isNaN(e)?0:e;this.staggerDelay=e+"ms"},f.removeElem=function(){this.element.parentNode.removeChild(this.element);this.css({display:""});this.emitEvent("remove",[this])},f.remove=function(){return b&&parseFloat(this.layout.options.transitionDuration)?(this.once("transitionEnd",function(){this.removeElem()}),void this.hide()):
void this.removeElem()},f.reveal=function(){delete this.isHidden;this.css({display:""});var e=this.layout.options,c={},n=this.getHideRevealTransitionEndProperty("visibleStyle");c[n]=this.onRevealTransitionEnd;this.transition({from:e.hiddenStyle,to:e.visibleStyle,isCleaning:!0,onTransitionEnd:c})},f.onRevealTransitionEnd=function(){this.isHidden||this.emitEvent("reveal")},f.getHideRevealTransitionEndProperty=function(e){e=this.layout.options[e];if(e.opacity)return"opacity";for(var c in e)return c},
f.hide=function(){this.isHidden=!0;this.css({display:""});var e=this.layout.options,c={},n=this.getHideRevealTransitionEndProperty("hiddenStyle");c[n]=this.onHideTransitionEnd;this.transition({from:e.visibleStyle,to:e.hiddenStyle,isCleaning:!0,onTransitionEnd:c})},f.onHideTransitionEnd=function(){this.isHidden&&(this.css({display:"none"}),this.emitEvent("hide"))},f.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},r});
(function(m,p){"function"==typeof define&&define.amd?define("outlayer/outlayer",["ev-emitter/ev-emitter","get-size/get-size","fizzy-ui-utils/utils","./item"],function(r,l,b,g){return p(m,r,l,b,g)}):"object"==typeof module&&module.exports?module.exports=p(m,require("ev-emitter"),require("get-size"),require("fizzy-ui-utils"),require("./item")):m.Outlayer=p(m,m.EvEmitter,m.getSize,m.fizzyUIUtils,m.Outlayer.Item)})(window,function(m,p,r,l,b){function g(a,d){var h=l.getQueryElement(a);if(!h)return void(f&&
f.error("Bad element for "+this.constructor.namespace+": "+(h||a)));this.element=h;u&&(this.$element=u(this.element));this.options=l.extend({},this.constructor.defaults);this.option(d);h=++q;this.element.outlayerGUID=h;e[h]=this;this._create();this._getOption("initLayout")&&this.layout()}function k(a){function d(){a.apply(this,arguments)}return d.prototype=Object.create(a.prototype),d.prototype.constructor=d,d}var f=m.console,u=m.jQuery,t=function(){},q=0,e={};g.namespace="outlayer";g.Item=b;g.defaults=
{containerStyle:{position:"relative"},initLayout:!0,originLeft:!0,originTop:!0,resize:!0,resizeContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}};var c=g.prototype;l.extend(c,p.prototype);c.option=function(a){l.extend(this.options,a)};c._getOption=function(a){var d=this.constructor.compatOptions[a];return d&&void 0!==this.options[d]?this.options[d]:this.options[a]};g.compatOptions={initLayout:"isInitLayout",horizontal:"isHorizontal",
layoutInstant:"isLayoutInstant",originLeft:"isOriginLeft",originTop:"isOriginTop",resize:"isResizeBound",resizeContainer:"isResizingContainer"};c._create=function(){this.reloadItems();this.stamps=[];this.stamp(this.options.stamp);l.extend(this.element.style,this.options.containerStyle);this._getOption("resize")&&this.bindResize()};c.reloadItems=function(){this.items=this._itemize(this.element.children)};c._itemize=function(a){a=this._filterFindItemElements(a);for(var d=this.constructor.Item,h=[],
v=0;v<a.length;v++){var w=new d(a[v],this);h.push(w)}return h};c._filterFindItemElements=function(a){return l.filterFindElements(a,this.options.itemSelector)};c.getItemElements=function(){return this.items.map(function(a){return a.element})};c.layout=function(){this._resetLayout();this._manageStamps();var a=this._getOption("layoutInstant");this.layoutItems(this.items,void 0!==a?a:!this._isLayoutInited);this._isLayoutInited=!0};c._init=c.layout;c._resetLayout=function(){this.getSize()};c.getSize=function(){this.size=
r(this.element)};c._getMeasurement=function(a,d){var h,v=this.options[a];v?("string"==typeof v?h=this.element.querySelector(v):v instanceof HTMLElement&&(h=v),this[a]=h?r(h)[d]:v):this[a]=0};c.layoutItems=function(a,d){a=this._getItemsForLayout(a);this._layoutItems(a,d);this._postLayout()};c._getItemsForLayout=function(a){return a.filter(function(d){return!d.isIgnored})};c._layoutItems=function(a,d){if(this._emitCompleteOnItems("layout",a),a&&a.length){var h=[];a.forEach(function(v){var w=this._getItemLayoutPosition(v);
w.item=v;w.isInstant=d||v.isLayoutInstant;h.push(w)},this);this._processLayoutQueue(h)}};c._getItemLayoutPosition=function(){return{x:0,y:0}};c._processLayoutQueue=function(a){this.updateStagger();a.forEach(function(d,h){this._positionItem(d.item,d.x,d.y,d.isInstant,h)},this)};c.updateStagger=function(){var a=this.options.stagger;if(null===a||void 0===a)a=void(this.stagger=0);else{if("number"!=typeof a){var d=a.match(/(^\d*\.?\d*)(\w*)/);a=d&&d[1];d=d&&d[2];a.length?(a=parseFloat(a),a*=n[d]||1):a=
0}a=(this.stagger=a,this.stagger)}return a};c._positionItem=function(a,d,h,v,w){v?a.goTo(d,h):(a.stagger(w*this.stagger),a.moveTo(d,h))};c._postLayout=function(){this.resizeContainer()};c.resizeContainer=function(){if(this._getOption("resizeContainer")){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}};c._getContainerSize=t;c._setContainerMeasure=function(a,d){if(void 0!==a){var h=this.size;h.isBorderBox&&(a+=d?h.paddingLeft+h.paddingRight+
h.borderLeftWidth+h.borderRightWidth:h.paddingBottom+h.paddingTop+h.borderTopWidth+h.borderBottomWidth);a=Math.max(a,0);this.element.style[d?"width":"height"]=a+"px"}};c._emitCompleteOnItems=function(a,d){function h(){w.dispatchEvent(a+"Complete",null,[d])}function v(){y++;y==x&&h()}var w=this,x=d.length;if(!d||!x)return void h();var y=0;d.forEach(function(z){z.once(a,v)})};c.dispatchEvent=function(a,d,h){var v=d?[d].concat(h):h;if(this.emitEvent(a,v),u)(this.$element=this.$element||u(this.element),
d)?(d=u.Event(d),d.type=a,this.$element.trigger(d,h)):this.$element.trigger(a,h)};c.ignore=function(a){(a=this.getItem(a))&&(a.isIgnored=!0)};c.unignore=function(a){(a=this.getItem(a))&&delete a.isIgnored};c.stamp=function(a){(a=this._find(a))&&(this.stamps=this.stamps.concat(a),a.forEach(this.ignore,this))};c.unstamp=function(a){(a=this._find(a))&&a.forEach(function(d){l.removeFrom(this.stamps,d);this.unignore(d)},this)};c._find=function(a){return a?("string"==typeof a&&(a=this.element.querySelectorAll(a)),
l.makeArray(a)):void 0};c._manageStamps=function(){this.stamps&&this.stamps.length&&(this._getBoundingRect(),this.stamps.forEach(this._manageStamp,this))};c._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),d=this.size;this._boundingRect={left:a.left+d.paddingLeft+d.borderLeftWidth,top:a.top+d.paddingTop+d.borderTopWidth,right:a.right-(d.paddingRight+d.borderRightWidth),bottom:a.bottom-(d.paddingBottom+d.borderBottomWidth)}};c._manageStamp=t;c._getElementOffset=function(a){var d=
a.getBoundingClientRect(),h=this._boundingRect;a=r(a);return{left:d.left-h.left-a.marginLeft,top:d.top-h.top-a.marginTop,right:h.right-d.right-a.marginRight,bottom:h.bottom-d.bottom-a.marginBottom}};c.handleEvent=l.handleEvent;c.bindResize=function(){m.addEventListener("resize",this);this.isResizeBound=!0};c.unbindResize=function(){m.removeEventListener("resize",this);this.isResizeBound=!1};c.onresize=function(){this.resize()};l.debounceMethod(g,"onresize",100);c.resize=function(){this.isResizeBound&&
this.needsResizeLayout()&&this.layout()};c.needsResizeLayout=function(){var a=r(this.element);return this.size&&a&&a.innerWidth!==this.size.innerWidth};c.addItems=function(a){a=this._itemize(a);return a.length&&(this.items=this.items.concat(a)),a};c.appended=function(a){a=this.addItems(a);a.length&&(this.layoutItems(a,!0),this.reveal(a))};c.prepended=function(a){a=this._itemize(a);if(a.length){var d=this.items.slice(0);this.items=a.concat(d);this._resetLayout();this._manageStamps();this.layoutItems(a,
!0);this.reveal(a);this.layoutItems(d)}};c.reveal=function(a){if(this._emitCompleteOnItems("reveal",a),a&&a.length){var d=this.updateStagger();a.forEach(function(h,v){h.stagger(v*d);h.reveal()})}};c.hide=function(a){if(this._emitCompleteOnItems("hide",a),a&&a.length){var d=this.updateStagger();a.forEach(function(h,v){h.stagger(v*d);h.hide()})}};c.revealItemElements=function(a){a=this.getItems(a);this.reveal(a)};c.hideItemElements=function(a){a=this.getItems(a);this.hide(a)};c.getItem=function(a){for(var d=
0;d<this.items.length;d++){var h=this.items[d];if(h.element==a)return h}};c.getItems=function(a){a=l.makeArray(a);var d=[];return a.forEach(function(h){(h=this.getItem(h))&&d.push(h)},this),d};c.remove=function(a){a=this.getItems(a);this._emitCompleteOnItems("remove",a);a&&a.length&&a.forEach(function(d){d.remove();l.removeFrom(this.items,d)},this)};c.destroy=function(){var a=this.element.style;a.height="";a.position="";a.width="";this.items.forEach(function(d){d.destroy()});this.unbindResize();delete e[this.element.outlayerGUID];
delete this.element.outlayerGUID;u&&u.removeData(this.element,this.constructor.namespace)};g.data=function(a){return(a=(a=l.getQueryElement(a))&&a.outlayerGUID)&&e[a]};g.create=function(a,d){var h=k(g);return h.defaults=l.extend({},g.defaults),l.extend(h.defaults,d),h.compatOptions=l.extend({},g.compatOptions),h.namespace=a,h.data=g.data,h.Item=k(b),l.htmlInit(h,a),u&&u.bridget&&u.bridget(a,h),h};var n={ms:1,s:1E3};return g.Item=b,g});
(function(m,p){"function"==typeof define&&define.amd?define(["outlayer/outlayer","get-size/get-size"],p):"object"==typeof module&&module.exports?module.exports=p(require("outlayer"),require("get-size")):m.Masonry=p(m.Outlayer,m.getSize)})(window,function(m,p){var r=m.create("masonry");r.compatOptions.fitWidth="isFitWidth";var l=r.prototype;return l._resetLayout=function(){this.getSize();this._getMeasurement("columnWidth","outerWidth");this._getMeasurement("gutter","outerWidth");this.measureColumns();
this.colYs=[];for(var b=0;b<this.cols;b++)this.colYs.push(0);this.horizontalColIndex=this.maxY=0},l.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var b=this.items[0];this.columnWidth=(b=b&&b.element)&&p(b).outerWidth||this.containerWidth}b=this.columnWidth+=this.gutter;var g=this.containerWidth+this.gutter,k=b-g%b;b=Math[k&&1>k?"round":"floor"](g/b);this.cols=Math.max(b,1)},l.getContainerWidth=function(){var b=this._getOption("fitWidth")?this.element.parentNode:this.element;
this.containerWidth=(b=p(b))&&b.innerWidth},l._getItemLayoutPosition=function(b){b.getSize();var g=b.size.outerWidth%this.columnWidth,k=Math[g&&1>g?"round":"ceil"](b.size.outerWidth/this.columnWidth);k=Math.min(k,this.cols);var f=this[this.options.horizontalOrder?"_getHorizontalColPosition":"_getTopColPosition"](k,b);g={x:this.columnWidth*f.col,y:f.y};b=f.y+b.size.outerHeight;k+=f.col;for(f=f.col;k>f;f++)this.colYs[f]=b;return g},l._getTopColPosition=function(b){b=this._getTopColGroup(b);var g=Math.min.apply(Math,
b);return{col:b.indexOf(g),y:g}},l._getTopColGroup=function(b){if(2>b)return this.colYs;for(var g=[],k=this.cols+1-b,f=0;k>f;f++)g[f]=this._getColGroupY(f,b);return g},l._getColGroupY=function(b,g){if(2>g)return this.colYs[b];var k=this.colYs.slice(b,b+g);return Math.max.apply(Math,k)},l._getHorizontalColPosition=function(b,g){var k=this.horizontalColIndex%this.cols;k=1<b&&k+b>this.cols?0:k;return this.horizontalColIndex=g.size.outerWidth&&g.size.outerHeight?k+b:this.horizontalColIndex,{col:k,y:this._getColGroupY(k,
b)}},l._manageStamp=function(b){var g=p(b),k=this._getElementOffset(b);b=this._getOption("originLeft")?k.left:k.right;var f=b+g.outerWidth,u=Math.floor(b/this.columnWidth);u=Math.max(0,u);b=Math.floor(f/this.columnWidth);b-=f%this.columnWidth?0:1;b=Math.min(this.cols-1,b);g=(this._getOption("originTop")?k.top:k.bottom)+g.outerHeight;for(k=u;b>=k;k++)this.colYs[k]=Math.max(g,this.colYs[k])},l._getContainerSize=function(){this.maxY=Math.max.apply(Math,this.colYs);var b={height:this.maxY};return this._getOption("fitWidth")&&
(b.width=this._getContainerFitWidth()),b},l._getContainerFitWidth=function(){for(var b=0,g=this.cols;--g&&0===this.colYs[g];)b++;return(this.cols-b)*this.columnWidth-this.gutter},l.needsResizeLayout=function(){var b=this.containerWidth;return this.getContainerWidth(),b!=this.containerWidth},r});